// ============================================================
// MCP Server Code Generator
// Generates a complete, production-ready MCP server project
// containing ONLY the user-selected Rocket.Chat API tools.
// ============================================================

import * as fs from "fs";
import * as path from "path";
import Handlebars from "handlebars";
import { ApiEndpoint } from "../registry/endpoints";

// ── Handlebars Helpers ──────────────────────────────────────
Handlebars.registerHelper("json", (context: any) => JSON.stringify(context, null, 2));
Handlebars.registerHelper("eq", (a: any, b: any) => a === b);
Handlebars.registerHelper("camelCase", (str: string) =>
    str.replace(/[.-](\w)/g, (_, c) => c.toUpperCase())
);
Handlebars.registerHelper("zodType", (type: string) => {
    switch (type) {
        case "string": return "z.string()";
        case "number": return "z.number()";
        case "boolean": return "z.boolean()";
        case "object": return "z.record(z.any())";
        case "array": return "z.array(z.any())";
        default: return "z.string()";
    }
});

export interface GeneratorOptions {
    endpoints: ApiEndpoint[];
    outputDir: string;
    serverName?: string;
}

export async function generateMcpServer(options: GeneratorOptions): Promise<void> {
    const { endpoints, outputDir, serverName = "rocketchat-mcp-server" } = options;

    // Create output directory
    fs.mkdirSync(outputDir, { recursive: true });

    // 1. Generate package.json
    const packageJson = generatePackageJson(serverName);
    fs.writeFileSync(path.join(outputDir, "package.json"), packageJson, "utf-8");

    // 2. Generate tsconfig.json
    const tsConfig = generateTsConfig();
    fs.writeFileSync(path.join(outputDir, "tsconfig.json"), tsConfig, "utf-8");

    // 3. Generate the MCP server source
    const srcDir = path.join(outputDir, "src");
    fs.mkdirSync(srcDir, { recursive: true });
    const serverCode = generateServerCode(endpoints, serverName);
    fs.writeFileSync(path.join(srcDir, "server.ts"), serverCode, "utf-8");

    // 4. Generate README
    const readme = generateReadme(endpoints, serverName);
    fs.writeFileSync(path.join(outputDir, "README.md"), readme, "utf-8");

    console.log(`\n✅ Generated MCP server in: ${path.resolve(outputDir)}`);
    console.log(`   Tools: ${endpoints.length} (out of 30 available)`);
    console.log(`\n   Next steps:`);
    console.log(`   cd ${outputDir}`);
    console.log(`   npm install`);
    console.log(`   npx ts-node src/server.ts`);
}

// ── package.json Generator ──────────────────────────────────
function generatePackageJson(name: string): string {
    const pkg = {
        name,
        version: "1.0.0",
        description: `Minimal MCP server for Rocket.Chat — auto-generated by rc-mcp-generator`,
        main: "dist/server.js",
        scripts: {
            build: "tsc",
            start: "ts-node src/server.ts",
            "start:built": "node dist/server.js",
        },
        dependencies: {
            "@modelcontextprotocol/sdk": "^1.12.1",
            zod: "^3.23.0",
        },
        devDependencies: {
            typescript: "^5.4.0",
            "ts-node": "^10.9.2",
            "@types/node": "^20.11.0",
        },
    };
    return JSON.stringify(pkg, null, 2) + "\n";
}

// ── tsconfig.json Generator ─────────────────────────────────
function generateTsConfig(): string {
    const config = {
        compilerOptions: {
            target: "ES2020",
            module: "commonjs",
            lib: ["ES2020"],
            outDir: "./dist",
            rootDir: "./src",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            resolveJsonModule: true,
            sourceMap: true,
        },
        include: ["src/**/*"],
        exclude: ["node_modules", "dist"],
    };
    return JSON.stringify(config, null, 2) + "\n";
}

// ── Server Code Generator ───────────────────────────────────
function generateServerCode(endpoints: ApiEndpoint[], serverName: string): string {
    const toolBlocks = endpoints.map((ep) => generateToolBlock(ep)).join("\n\n");

    return `#!/usr/bin/env node
// ============================================================
// ${serverName}
// Auto-generated by rc-mcp-generator
// Tools: ${endpoints.length} | Categories: ${[...new Set(endpoints.map((e) => e.category))].join(", ")}
// ============================================================

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

// ── Configuration ───────────────────────────────────────────
const RC_URL = process.env.ROCKETCHAT_URL || "http://localhost:3000";
let authToken = "";
let userId = "";

// ── HTTP Helper ─────────────────────────────────────────────
async function rcApi(method: string, path: string, body?: any, query?: Record<string, string>): Promise<any> {
  const url = new URL(path, RC_URL);
  if (query) {
    Object.entries(query).forEach(([k, v]) => {
      if (v !== undefined && v !== null && v !== "") url.searchParams.set(k, String(v));
    });
  }

  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (authToken && userId) {
    headers["X-Auth-Token"] = authToken;
    headers["X-User-Id"] = userId;
  }

  const res = await fetch(url.toString(), {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  const data = await res.json();
  if (!res.ok) throw new Error(\`RC API error \${res.status}: \${JSON.stringify(data)}\`);
  return data;
}

// ── MCP Server ──────────────────────────────────────────────
const server = new McpServer({
  name: "${serverName}",
  version: "1.0.0",
});

// ── Tool Definitions ────────────────────────────────────────
${toolBlocks}

// ── Start Server ────────────────────────────────────────────
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(\`🚀 \${server.server.name} running on stdio — ${endpoints.length} tools loaded\`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
`;
}

// ── Individual Tool Block Generator ─────────────────────────
function generateToolBlock(ep: ApiEndpoint): string {
    const fnName = ep.id.replace(/[.-]/g, "_");

    // Build Zod schema entries
    const schemaEntries = ep.parameters.map((p) => {
        const zodBase = getZodType(p.type);
        const zodFull = p.required ? zodBase : `${zodBase}.optional()`;
        return `    ${p.name}: ${zodFull}.describe("${p.description}")`;
    });

    const schemaBlock =
        schemaEntries.length > 0
            ? `{\n${schemaEntries.join(",\n")}\n  }`
            : `{}`;

    // Build the handler body
    let handlerBody: string;
    if (ep.id === "login") {
        handlerBody = `
      const result = await rcApi("${ep.method}", "${ep.path}", { user: args.user, password: args.password });
      authToken = result.data?.authToken || "";
      userId = result.data?.userId || "";
      return { content: [{ type: "text" as const, text: JSON.stringify({ success: true, userId, message: "Logged in successfully" }, null, 2) }] };`;
    } else if (ep.id === "logout") {
        handlerBody = `
      const result = await rcApi("${ep.method}", "${ep.path}");
      authToken = "";
      userId = "";
      return { content: [{ type: "text" as const, text: JSON.stringify({ success: true, message: "Logged out" }, null, 2) }] };`;
    } else if (ep.method === "GET") {
        const queryParams = ep.parameters.map((p) => `${p.name}: args.${p.name} as any`).join(", ");
        handlerBody = `
      const result = await rcApi("${ep.method}", "${ep.path}", undefined, { ${queryParams} });
      return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };`;
    } else {
        handlerBody = `
      const result = await rcApi("${ep.method}", "${ep.path}", args);
      return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };`;
    }

    return `// Tool: ${ep.id} — ${ep.description}
server.tool(
  "${ep.id}",
  "${ep.description}",
  ${schemaBlock},
  async (args) => {${handlerBody}
  }
);`;
}

function getZodType(type: string): string {
    switch (type) {
        case "string": return "z.string()";
        case "number": return "z.number()";
        case "boolean": return "z.boolean()";
        case "object": return "z.record(z.any())";
        case "array": return "z.array(z.any())";
        default: return "z.string()";
    }
}

// ── README Generator ────────────────────────────────────────
function generateReadme(endpoints: ApiEndpoint[], serverName: string): string {
    const categories = [...new Set(endpoints.map((e) => e.category))];
    const toolTable = endpoints
        .map((e) => `| \`${e.id}\` | ${e.method} | \`${e.path}\` | ${e.description.slice(0, 60)} |`)
        .join("\n");

    return `# ${serverName}

> Auto-generated minimal MCP server for Rocket.Chat.  
> **${endpoints.length} tools** across ${categories.length} categories — lean by design.

## Quick Start

\`\`\`bash
npm install
npx ts-node src/server.ts
\`\`\`

## Environment Variables

| Variable | Description | Default |
|----------|-------------|---------|
| \`ROCKETCHAT_URL\` | Your Rocket.Chat server URL | \`http://localhost:3000\` |

## Available Tools

| Tool | Method | Path | Description |
|------|--------|------|-------------|
${toolTable}

## Why Minimal?

This server includes only ${endpoints.length} out of 30+ available Rocket.Chat API endpoints.
Fewer tools = smaller context window = cheaper + faster + more accurate AI agent responses.

---

*Generated by [rc-mcp-generator](https://github.com/saadkhan/rc-mcp-generator)*
`;
}
